spring:
  application:
    name: config-server
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///E:/projects/microservices-configs
          clone-on-start: true
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,configprops
  endpoint:
    health:
      show-details: always
