server:
  port: 8761
  ssl:
    enabled: false

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    renewal-percent-threshold: 0.50
